# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        # pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      run: |
        source venv/bin/activate
        python ovify.py
        python main.py -i "This framework provides an easy method to compute dense vector representations for sentences, paragraphs, and images." 
        python main.py -i "To check if a given number is infinite or not, one can use isinf() method of the math library which returns a boolean value." 
        python main.py -i "As positive infinity is always bigger than every natural number and negative infinity is always smaller than negative numbers."

